############ FAILURE ############
ios_banner : Set login again (idempotent)/Users/dnewswan/code/ansible/test/integration/targets/ios_banner/tests/cli/basic-login.yaml:30

[_ansible_parsed]=> True
[_ansible_no_log]=> False
[err]=> [Errno 2] No such file or directory
[changed]=> False
[failed]=> True
[invocation]=> {u'module_args': {u'authorize': True, u'username': None, u'ssh_keyfile': None, u'text': u'this is my login banner\nthat has a multiline\nstring\n', u'auth_pass': None, u'state': u'present', u'host': None, u'timeout': None, u'provider': {u'username': u'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER', u'authorize': True, u'ssh_keyfile': None, u'auth_pass': None, u'host': u'ios01', u'timeout': None, u'password': u'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER', u'port': None, u'transport': u'cli'}, u'password': None, u'banner': u'login', u'port': None}}
[msg]=> unable to connect to socket



############ IGNORED ############
See /Users/dnewswan/code/ansible/test/integration/targets/ios_command/tests/cli/bad_operator.yaml:4 if you think this is a problem 


############ FAILURE ############
ios_command : test contains operator/Users/dnewswan/code/ansible/test/integration/targets/ios_command/tests/cli/contains.yaml:4

[msg]=> unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell
[failed]=> True
[changed]=> False
[_ansible_no_log]=> False



############ FAILURE ############
ios_config : setup/Users/dnewswan/code/ansible/test/integration/targets/ios_config/tests/cli/backup.yaml:4

[msg]=> unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell
[failed]=> True
[changed]=> False
[_ansible_no_log]=> False



############ FAILURE ############
ios_facts : test getting all facts/Users/dnewswan/code/ansible/test/integration/targets/ios_facts/tests/cli/all_facts.yaml:5

[msg]=> unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell
[failed]=> True
[changed]=> False
[_ansible_no_log]=> False



############ IGNORED ############
See /Users/dnewswan/code/ansible/test/integration/targets/ios_template/tests/cli/backup.yaml:4 if you think this is a problem 


############ FAILURE ############
ios_template : configure device with config/Users/dnewswan/code/ansible/test/integration/targets/ios_template/tests/cli/backup.yaml:24

[msg]=> unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell
[failed]=> True
[changed]=> False
[_ansible_no_log]=> False



############ FAILURE ############
prepare_ios_tests : Ensure we have loopback 888 for testing/Users/dnewswan/code/ansible/test/integration/targets/prepare_ios_tests/tasks/main.yml:3

[_ansible_parsed]=> True
[stderr_lines]=> [u'show running-config', u'                ^', u"% Invalid input detected at '^' marker.", u'', u'ios01(config)#']
[_ansible_no_log]=> False
[changed]=> False
[failed]=> True
[stderr]=> show running-config
                ^
% Invalid input detected at '^' marker.

ios01(config)#
[invocation]=> {u'module_args': {u'multiline_delimiter': u'@', u'authorize': None, u'force': False, u'diff_against': None, u'replace': u'line', u'running_config': None, u'save_when': u'never', u'port': None, u'before': None, u'auth_pass': None, u'parents': None, u'provider': {u'username': u'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER', u'authorize': None, u'ssh_keyfile': None, u'auth_pass': None, u'host': u'ios01', u'timeout': None, u'password': u'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER', u'port': None, u'transport': u'cli'}, u'save': False, u'match': u'line', u'username': None, u'timeout': None, u'after': None, u'host': None, u'password': None, u'diff_ignore_lines': None, u'src': u'interface Loopback888\n description test for ansible\n shutdown\n\n', u'ssh_keyfile': None, u'lines': None, u'intended_config': None, u'defaults': False, u'backup': False}}
[msg]=> unable to retrieve current config



############ FAILURE ############
ios_user : Create user (SetUp)/Users/dnewswan/code/ansible/test/integration/targets/ios_user/tests/cli/basic.yaml:2

[_ansible_parsed]=> True
[_ansible_no_log]=> False
[err]=> [Errno 2] No such file or directory
[changed]=> False
[failed]=> True
[invocation]=> {u'module_args': {u'authorize': True, u'username': None, u'update_password': u'always', u'ssh_keyfile': None, u'users': None, u'auth_pass': None, u'host': None, u'purge': False, u'privilege': 15, u'state': u'present', u'role': u'network-operator', u'timeout': None, u'provider': {u'username': u'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER', u'authorize': True, u'ssh_keyfile': None, u'auth_pass': None, u'host': u'ios01', u'timeout': None, u'password': u'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER', u'port': None, u'transport': u'cli'}, u'nopassword': None, u'password': None, u'view': u'network-operator', u'port': None, u'name': u'ansibletest1'}}
[msg]=> unable to connect to socket



############ FAILURE ############
ios_static_route : create static route/Users/dnewswan/code/ansible/test/integration/targets/ios_static_route/tests/cli/basic.yaml:2

[_ansible_parsed]=> True
[_ansible_no_log]=> False
[err]=> [Errno 61] Connection refused
[changed]=> False
[failed]=> True
[invocation]=> {u'module_args': {u'authorize': True, u'username': None, u'ssh_keyfile': None, u'state': u'present', u'auth_pass': None, u'mask': u'255.255.255.0', u'host': None, u'collection': None, u'admin_distance': 1, u'purge': None, u'prefix': u'172.16.31.0', u'next_hop': u'10.0.0.8', u'timeout': None, u'provider': {u'username': u'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER', u'authorize': True, u'ssh_keyfile': None, u'auth_pass': None, u'host': u'ios01', u'timeout': None, u'password': u'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER', u'port': None, u'transport': u'cli'}, u'password': None, u'port': None}}
[msg]=> unable to connect to socket



############ FAILURE ############
prepare_ios_tests : Ensure we have loopback 888 for testing/Users/dnewswan/code/ansible/test/integration/targets/prepare_ios_tests/tasks/main.yml:3

[_ansible_parsed]=> True
[_ansible_no_log]=> False
[err]=> [Errno 2] No such file or directory
[changed]=> False
[failed]=> True
[invocation]=> {u'module_args': {u'multiline_delimiter': u'@', u'authorize': None, u'force': False, u'diff_against': None, u'replace': u'line', u'running_config': None, u'save_when': u'never', u'port': None, u'before': None, u'auth_pass': None, u'parents': None, u'provider': {u'username': u'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER', u'authorize': None, u'ssh_keyfile': None, u'auth_pass': None, u'host': u'ios01', u'timeout': None, u'password': u'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER', u'port': None, u'transport': u'cli'}, u'save': False, u'match': u'line', u'username': None, u'timeout': None, u'after': None, u'host': None, u'password': None, u'diff_ignore_lines': None, u'src': u'interface Loopback888\n description test for ansible\n shutdown\n\n', u'ssh_keyfile': None, u'lines': None, u'intended_config': None, u'defaults': False, u'backup': False}}
[msg]=> unable to connect to socket



############ FAILURE ############
Has any previous test failed?/Users/dnewswan/code/ansible/test/integration/ios.yaml:102

[msg]=> One or more tests failed, check log for details
[failed]=> True
[changed]=> False
[_ansible_no_log]=> False



############ FAILURE ############
ios_banner : assert/Users/dnewswan/code/ansible/test/integration/targets/ios_banner/tests/cli/basic-login.yaml:25

[_ansible_no_log]=> False
[changed]=> False
[assertion]=> result.changed == true
[_ansible_verbose_always]=> True
[failed]=> True
[evaluated_to]=> False



############ FAILURE ############
prepare_ios_tests : Ensure we have loopback 888 for testing/Users/dnewswan/code/ansible/test/integration/targets/prepare_ios_tests/tasks/main.yml:3

[_ansible_parsed]=> True
[_ansible_no_log]=> False
[err]=> [Errno 2] No such file or directory
[changed]=> False
[failed]=> True
[invocation]=> {u'module_args': {u'multiline_delimiter': u'@', u'authorize': None, u'force': False, u'diff_against': None, u'replace': u'line', u'running_config': None, u'save_when': u'never', u'port': None, u'before': None, u'auth_pass': None, u'parents': None, u'provider': {u'username': u'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER', u'authorize': None, u'ssh_keyfile': None, u'auth_pass': None, u'host': u'ios01', u'timeout': None, u'password': u'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER', u'port': None, u'transport': u'cli'}, u'save': False, u'match': u'line', u'username': None, u'timeout': None, u'after': None, u'host': None, u'password': None, u'diff_ignore_lines': None, u'src': u'interface Loopback888\n description test for ansible\n shutdown\n\n', u'ssh_keyfile': None, u'lines': None, u'intended_config': None, u'defaults': False, u'backup': False}}
[msg]=> unable to connect to socket



############ IGNORED ############
See /Users/dnewswan/code/ansible/test/integration/targets/ios_config/tests/cli/save.yaml:21 if you think this is a problem 


############ IGNORED ############
See /Users/dnewswan/code/ansible/test/integration/targets/ios_config/tests/cli/save.yaml:34 if you think this is a problem 


############ IGNORED ############
See /Users/dnewswan/code/ansible/test/integration/targets/ios_config/tests/cli/src_invalid.yaml:6 if you think this is a problem 


############ FAILURE ############
ios_config : configure sub level command idempotent check/Users/dnewswan/code/ansible/test/integration/targets/ios_config/tests/cli/sublevel.yaml:23

[_ansible_parsed]=> False
[_ansible_no_log]=> False
[module_stderr]=> Traceback (most recent call last):
  File "/var/folders/ql/d9_087wj4cd10grvwzxmk4hc0000gn/T/ansible_GPFhdY/ansible_module_ios_config.py", line 530, in <module>
    main()
  File "/var/folders/ql/d9_087wj4cd10grvwzxmk4hc0000gn/T/ansible_GPFhdY/ansible_module_ios_config.py", line 438, in main
    config, have_banners = get_running_config(module, config)
  File "/var/folders/ql/d9_087wj4cd10grvwzxmk4hc0000gn/T/ansible_GPFhdY/ansible_module_ios_config.py", line 347, in get_running_config
    contents = get_config(module, flags=flags)
  File "/var/folders/ql/d9_087wj4cd10grvwzxmk4hc0000gn/T/ansible_GPFhdY/ansible_modlib.zip/ansible/module_utils/ios.py", line 91, in get_config
  File "/var/folders/ql/d9_087wj4cd10grvwzxmk4hc0000gn/T/ansible_GPFhdY/ansible_modlib.zip/ansible/module_utils/connection.py", line 72, in exec_command
TypeError: int() can't convert non-string with explicit base

[changed]=> False
[module_stdout]=> 
[failed]=> True
[rc]=> 0
[msg]=> MODULE FAILURE



############ FAILURE ############
ios_facts : test getting default facts/Users/dnewswan/code/ansible/test/integration/targets/ios_facts/tests/cli/default_facts.yaml:5

[_ansible_parsed]=> True
[_ansible_no_log]=> False
[err]=> [Errno 2] No such file or directory
[changed]=> False
[failed]=> True
[invocation]=> {u'module_args': {u'username': None, u'authorize': None, u'ssh_keyfile': None, u'auth_pass': None, u'host': None, u'gather_subset': [u'!config'], u'timeout': None, u'provider': None, u'password': None, u'port': None}}
[msg]=> unable to connect to socket



############ IGNORED ############
See /Users/dnewswan/code/ansible/test/integration/targets/ios_template/tests/cli/basic.yaml:4 if you think this is a problem 


############ FAILURE ############
ios_template : configure device with config/Users/dnewswan/code/ansible/test/integration/targets/ios_template/tests/cli/basic.yaml:11

[_ansible_parsed]=> True
[stderr_lines]=> [u'show running-config all', u'                ^', u"% Invalid input detected at '^' marker.", u'', u'ios01(config)#']
[_ansible_no_log]=> False
[changed]=> False
[failed]=> True
[stderr]=> show running-config all
                ^
% Invalid input detected at '^' marker.

ios01(config)#
[invocation]=> {u'module_args': {u'username': None, u'src': u'interface Loopback999\n description this is a test\n shutdown\n\n', u'ssh_keyfile': None, u'force': False, u'backup': False, u'auth_pass': None, u'authorize': None, u'include_defaults': True, u'host': None, u'timeout': None, u'provider': None, u'password': None, u'config': None, u'port': None}}
[msg]=> unable to retrieve current config



############ FAILURE ############
prepare_ios_tests : Ensure we have loopback 888 for testing/Users/dnewswan/code/ansible/test/integration/targets/prepare_ios_tests/tasks/main.yml:3

[_ansible_parsed]=> True
[stderr_lines]=> [u'show running-config', u'                ^', u"% Invalid input detected at '^' marker.", u'', u'ios01(config)#']
[_ansible_no_log]=> False
[changed]=> False
[failed]=> True
[stderr]=> show running-config
                ^
% Invalid input detected at '^' marker.

ios01(config)#
[invocation]=> {u'module_args': {u'multiline_delimiter': u'@', u'authorize': None, u'force': False, u'diff_against': None, u'replace': u'line', u'running_config': None, u'save_when': u'never', u'port': None, u'before': None, u'auth_pass': None, u'parents': None, u'provider': {u'username': u'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER', u'authorize': None, u'ssh_keyfile': None, u'auth_pass': None, u'host': u'ios01', u'timeout': None, u'password': u'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER', u'port': None, u'transport': u'cli'}, u'save': False, u'match': u'line', u'username': None, u'timeout': None, u'after': None, u'host': None, u'password': None, u'diff_ignore_lines': None, u'src': u'interface Loopback888\n description test for ansible\n shutdown\n\n', u'ssh_keyfile': None, u'lines': None, u'intended_config': None, u'defaults': False, u'backup': False}}
[msg]=> unable to retrieve current config



############ FAILURE ############
prepare_ios_tests : Ensure we have loopback 888 for testing/Users/dnewswan/code/ansible/test/integration/targets/prepare_ios_tests/tasks/main.yml:3

[_ansible_parsed]=> True
[stderr_lines]=> [u'show running-config', u'                ^', u"% Invalid input detected at '^' marker.", u'', u'ios01(config)#']
[_ansible_no_log]=> False
[changed]=> False
[failed]=> True
[stderr]=> show running-config
                ^
% Invalid input detected at '^' marker.

ios01(config)#
[invocation]=> {u'module_args': {u'multiline_delimiter': u'@', u'authorize': None, u'force': False, u'diff_against': None, u'replace': u'line', u'running_config': None, u'save_when': u'never', u'port': None, u'before': None, u'auth_pass': None, u'parents': None, u'provider': {u'username': u'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER', u'authorize': None, u'ssh_keyfile': None, u'auth_pass': None, u'host': u'ios01', u'timeout': None, u'password': u'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER', u'port': None, u'transport': u'cli'}, u'save': False, u'match': u'line', u'username': None, u'timeout': None, u'after': None, u'host': None, u'password': None, u'diff_ignore_lines': None, u'src': u'interface Loopback888\n description test for ansible\n shutdown\n\n', u'ssh_keyfile': None, u'lines': None, u'intended_config': None, u'defaults': False, u'backup': False}}
[msg]=> unable to retrieve current config



############ FAILURE ############
prepare_ios_tests : Ensure we have loopback 888 for testing/Users/dnewswan/code/ansible/test/integration/targets/prepare_ios_tests/tasks/main.yml:3

[_ansible_parsed]=> True
[stderr_lines]=> [u'show running-config', u'                ^', u"% Invalid input detected at '^' marker.", u'', u'ios01(config)#']
[_ansible_no_log]=> False
[changed]=> False
[failed]=> True
[stderr]=> show running-config
                ^
% Invalid input detected at '^' marker.

ios01(config)#
[invocation]=> {u'module_args': {u'multiline_delimiter': u'@', u'authorize': None, u'force': False, u'diff_against': None, u'replace': u'line', u'running_config': None, u'save_when': u'never', u'port': None, u'before': None, u'auth_pass': None, u'parents': None, u'provider': {u'username': u'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER', u'authorize': None, u'ssh_keyfile': None, u'auth_pass': None, u'host': u'ios01', u'timeout': None, u'password': u'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER', u'port': None, u'transport': u'cli'}, u'save': False, u'match': u'line', u'username': None, u'timeout': None, u'after': None, u'host': None, u'password': None, u'diff_ignore_lines': None, u'src': u'interface Loopback888\n description test for ansible\n shutdown\n\n', u'ssh_keyfile': None, u'lines': None, u'intended_config': None, u'defaults': False, u'backup': False}}
[msg]=> unable to retrieve current config



############ FAILURE ############
prepare_ios_tests : Ensure we have loopback 888 for testing/Users/dnewswan/code/ansible/test/integration/targets/prepare_ios_tests/tasks/main.yml:3

[_ansible_parsed]=> True
[stderr_lines]=> [u'show running-config', u'                ^', u"% Invalid input detected at '^' marker.", u'', u'ios01(config)#']
[_ansible_no_log]=> False
[changed]=> False
[failed]=> True
[stderr]=> show running-config
                ^
% Invalid input detected at '^' marker.

ios01(config)#
[invocation]=> {u'module_args': {u'multiline_delimiter': u'@', u'authorize': None, u'force': False, u'diff_against': None, u'replace': u'line', u'running_config': None, u'save_when': u'never', u'port': None, u'before': None, u'auth_pass': None, u'parents': None, u'provider': {u'username': u'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER', u'authorize': None, u'ssh_keyfile': None, u'auth_pass': None, u'host': u'ios01', u'timeout': None, u'password': u'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER', u'port': None, u'transport': u'cli'}, u'save': False, u'match': u'line', u'username': None, u'timeout': None, u'after': None, u'host': None, u'password': None, u'diff_ignore_lines': None, u'src': u'interface Loopback888\n description test for ansible\n shutdown\n\n', u'ssh_keyfile': None, u'lines': None, u'intended_config': None, u'defaults': False, u'backup': False}}
[msg]=> unable to retrieve current config



############ FAILURE ############
Has any previous test failed?/Users/dnewswan/code/ansible/test/integration/ios.yaml:102

[msg]=> One or more tests failed, check log for details
[failed]=> True
[changed]=> False
[_ansible_no_log]=> False



